name: Rust

on: 
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Update Rust
              run: rustup update stable && rustup --version && rustc --version && cargo --version
            - name: Add clippy and fmt components
              run: rustup component add clippy rustfmt
            - name: Lint
              run: cargo fmt -- --check && cargo clippy
            - name: Build
              run: cargo build
            - name: Run tests
              run: cargo test
